# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"

  config.vm.provider "libvirt" do |v| 
    v.memory = 2048
    v.cpus = 8
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vm-provision.yml"
  end
end
