# This file isn't really needed, but Vagrant needs an ansible playbook for provisioning so that it creates an ansible inventory file, which can later be used for other playbooks
- hosts: all
  become: yes
  tasks:
    - name: Make sure python is installed
      yum:
        name: python3
        state: present
